version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: construction_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopass123
      MONGO_INITDB_DATABASE: construction_management
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - construction_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: construction_backend
    restart: always
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:mongopass123@mongodb:27017/construction_management?authSource=admin
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - construction_network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: construction_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - construction_network

volumes:
  mongodb_data:

networks:
  construction_network:
    driver: bridge
